# Generated by Django 4.2.17 on 2025-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_userinfo_options_alter_userinfo_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='temp_email', max_length=254),
        ),
    ]
