# Generated by Django 5.1.3 on 2025-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('raw_text', models.TextField()),
                ('structured_notes', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('raw_text_dict', models.TextField(null=True, blank=True)),
            ],
        ),
    ]
